Repository exercism/php, pull requests merged in 2021-03, with the labels that each got.

#350 🤖 Add docs configuration
  docs/config.json
Labels: v3-migration 🤖

#355 🤖 Flatten authors and contributors in .meta/config.json files
  exercises/practice/ordinal-number/.meta/config.json
Labels: v3-migration 🤖

#358 Flip assertEqauls() arguments
  exercises/practice/meetup/MeetupTest.php
Labels: reputation/contributed_code/medium

#360 remove phpunit 8 from readme
  README.md
  bin/install.sh
Labels: reputation/contributed_code/minor
