Repository exercism/php, pull requests merged in 2023-09, with the labels that each got.

#554 fix author of Say exercise
  exercises/practice/say/.meta/config.json
Labels: x:size/tiny, x:rep/tiny

#555 fix instructions typos for windowing-system
  exercises/concept/windowing-system/.docs/instructions.md
Labels: x:action/improve, x:size/tiny, x:rep/tiny

#557 Update instructions.md
  exercises/concept/city-office/.docs/instructions.md
Labels: x:action/improve, x:size/tiny, x:rep/tiny

#560 Convert backtick (`) admonition fences to tildes (~)
  exercises/practice/gigasecond/.docs/introduction.md
  exercises/practice/linked-list/.docs/instructions.md
  exercises/practice/pangram/.docs/introduction.md
  exercises/practice/sieve/.docs/instructions.md
Labels: x:size/tiny
