Repository exercism/php, pull requests merged in 2023-08, with the labels that each got.

#531 [fix] update pizza pi instructions for excersise number one
  exercises/concept/pizza-pi/.docs/instructions.md
Labels: x:type/content, x:size/tiny, x:rep/tiny

#533 Update README.md
  README.md
Labels: x:size/tiny, x:rep/tiny

#542 fix typo
  exercises/concept/pizza-pi/PizzaPiTest.php
Labels: x:size/tiny, x:rep/tiny

#545 language list imporvments
  exercises/concept/language-list/.docs/instructions.md
Labels: x:action/improve, x:size/tiny, x:rep/tiny

#546 fix: typos
  concepts/class-basics/about.md
  concepts/class-basics/introduction.md
  exercises/concept/windowing-system/.docs/instructions.md
  exercises/concept/windowing-system/.docs/introduction.md
Labels: x:action/improve, x:size/tiny, x:rep/tiny

#534 Add the Bank Account exercise
  config.json
  exercises/practice/bank-account/.docs/instructions.append.md
  exercises/practice/bank-account/.docs/instructions.md
  exercises/practice/bank-account/.meta/config.json
  exercises/practice/bank-account/.meta/example.php
  exercises/practice/bank-account/BankAccount.php
  exercises/practice/bank-account/BankAccountTest.php
Labels: x:module/practice-exercise, x:size/large, x:rep/large

#535 Add the proverb exercise.
  config.json
  exercises/practice/proverb/.docs/instructions.md
  exercises/practice/proverb/.meta/config.json
  exercises/practice/proverb/.meta/example.php
  exercises/practice/proverb/Proverb.php
  exercises/practice/proverb/ProverbTest.php
Labels: x:module/practice-exercise, x:size/large, x:rep/large

#536 Add the protein-translation exercise.
  config.json
  exercises/practice/protein-translation/.docs/instructions.md
  exercises/practice/protein-translation/.meta/config.json
  exercises/practice/protein-translation/.meta/example.php
  exercises/practice/protein-translation/ProteinTranslation.php
  exercises/practice/protein-translation/ProteinTranslationTest.php
Labels: x:module/practice-exercise, x:size/large, x:rep/large

#540 Add the twelve-days exercise.
  config.json
  exercises/practice/twelve-days/.docs/instructions.md
  exercises/practice/twelve-days/.meta/config.json
  exercises/practice/twelve-days/.meta/example.php
  exercises/practice/twelve-days/TwelveDays.php
  exercises/practice/twelve-days/TwelveDaysTest.php
Labels: x:module/practice-exercise

#541 Add the resistor-color-trio exercise.
  config.json
  exercises/practice/resistor-color-trio/.docs/instructions.md
  exercises/practice/resistor-color-trio/.meta/config.json
  exercises/practice/resistor-color-trio/.meta/example.php
  exercises/practice/resistor-color-trio/ResistorColorTrio.php
  exercises/practice/resistor-color-trio/ResistorColorTrioTest.php
Labels: x:module/practice-exercise, x:size/large, x:rep/large

#544 Update instructions.md
  exercises/concept/annalyns-infiltration/.docs/instructions.md
Labels: x:action/improve, x:size/tiny, x:rep/tiny

#549 fix: typo in word "single" in test name
  exercises/practice/variable-length-quantity/VariableLengthQuantityTest.php
Labels: x:size/tiny, x:rep/tiny

#548 fix: several typos in concepts
  concepts/basic-syntax/about.md
  concepts/basic-syntax/introduction.md
  concepts/class-basics/about.md
  concepts/class-basics/introduction.md
  concepts/class-visibility/about.md
  concepts/class-visibility/introduction.md
  concepts/covariance-and-contravariance/about.md
  concepts/floating-point-numbers/about.md
  concepts/floating-point-numbers/introduction.md
  concepts/null-values/about.md
  concepts/null-values/introduction.md
  concepts/strings/about.md
  concepts/strings/introduction.md
  concepts/type-declaration/introduction.md
  concepts/union-types/introduction.md
  concepts/user-defined-functions/about.md
  concepts/user-defined-functions/introduction.md
  exercises/concept/city-office/.docs/introduction.md
  exercises/concept/language-list/.docs/instructions.md
  exercises/concept/language-list/LanguageListTest.php
  exercises/concept/lasagna/.docs/introduction.md
  exercises/concept/pizza-pi/.docs/instructions.md
  exercises/concept/pizza-pi/.docs/introduction.md
  exercises/concept/sweethearts/.docs/introduction.md
  exercises/concept/windowing-system/.docs/introduction.md
Labels: x:size/tiny, x:rep/tiny

#551 Add Yacht exercise to track.
  config.json
  exercises/practice/yacht/.docs/instructions.md
  exercises/practice/yacht/.meta/config.json
  exercises/practice/yacht/.meta/example.php
  exercises/practice/yacht/Yacht.php
  exercises/practice/yacht/YachtTest.php
Labels: x:module/practice-exercise

#553 Add Say exercise to track
  config.json
  exercises/practice/say/.docs/instructions.md
  exercises/practice/say/.meta/config.json
  exercises/practice/say/.meta/example.php
  exercises/practice/say/Say.php
  exercises/practice/say/SayTest.php
Labels: x:module/practice-exercise
