Repository exercism/php, pull requests merged in 2024-01, with the labels that each got.

#596 Update instructions.md
  exercises/concept/lasagna/.docs/instructions.md
Labels: x:action/improve, x:type/content, x:size/tiny, x:rep/tiny

#598 leap: sync
  exercises/practice/leap/.docs/instructions.md
  exercises/practice/leap/.docs/introduction.md
  exercises/practice/leap/.meta/config.json
Labels: x:size/tiny

#599 Fix a typo
  exercises/concept/language-list/.docs/hints.md
  exercises/concept/lasagna/.docs/instructions.md
  exercises/concept/sweethearts/.docs/hints.md
Labels: x:type/content, x:size/tiny, x:rep/tiny

#600 reverse-string: sync
  exercises/practice/reverse-string/.docs/instructions.md
  exercises/practice/reverse-string/.docs/introduction.md
  exercises/practice/reverse-string/.meta/config.json
Labels: x:size/tiny

#604 Task association of Position test and minor fixes to Windowing system concept exercise
  concepts/class-basics/introduction.md
  exercises/concept/windowing-system/.docs/hints.md
  exercises/concept/windowing-system/.docs/instructions.md
  exercises/concept/windowing-system/.docs/introduction.md
  exercises/concept/windowing-system/ProgramWindowTest.php
Labels: x:type/content, x:size/small, x:rep/small

#606 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny
