Repository exercism/php, pull requests merged in 2024-04, with the labels that each got.

#680 Sync scrabble score
  exercises/practice/scrabble-score/.docs/instructions.md
  exercises/practice/scrabble-score/.docs/introduction.md
  exercises/practice/scrabble-score/.meta/config.json
  exercises/practice/scrabble-score/.meta/example.php
  exercises/practice/scrabble-score/ScrabbleScoreTest.php
Labels: x:action/sync, x:knowledge/elementary, x:module/practice-exercise, x:type/content, x:size/small, x:rep/small

#689 Sync pangram
  exercises/practice/pangram/.docs/instructions.md
  exercises/practice/pangram/.meta/example.php
  exercises/practice/pangram/.meta/tests.toml
  exercises/practice/pangram/PangramTest.php
Labels: x:action/sync, x:knowledge/elementary, x:module/practice-exercise, x:type/content, x:size/small, x:rep/small

#683 Test timeout issues
  bin/test.sh
  exercises/practice/robot-name/RobotNameTest.php
Labels: x:action/fix, x:knowledge/intermediate, x:type/ci, x:type/content, x:size/medium, x:rep/medium

#685 zebra-puzzle: sync
  exercises/practice/zebra-puzzle/.docs/instructions.md
  exercises/practice/zebra-puzzle/.docs/introduction.md
Labels: x:size/tiny, paused

#686 minesweeper: sync
  exercises/practice/minesweeper/.docs/instructions.md
  exercises/practice/minesweeper/.docs/introduction.md
  exercises/practice/minesweeper/.meta/config.json
Labels: x:size/tiny, paused

#687 dnd-character: sync
  exercises/practice/dnd-character/.docs/instructions.md
  exercises/practice/dnd-character/.docs/introduction.md
  exercises/practice/dnd-character/.meta/config.json
Labels: x:size/tiny, paused

#694 Sync All your base
  exercises/practice/all-your-base/.docs/instructions.md
  exercises/practice/all-your-base/.docs/introduction.md
  exercises/practice/all-your-base/.meta/example.php
  exercises/practice/all-your-base/.meta/tests.toml
  exercises/practice/all-your-base/AllYourBase.php
  exercises/practice/all-your-base/AllYourBaseTest.php
Labels: x:action/sync, x:knowledge/elementary, x:module/practice-exercise, x:type/content, x:size/medium, x:rep/medium

#698 yacht: sync
  exercises/practice/yacht/.docs/instructions.md
  exercises/practice/yacht/.docs/introduction.md
  exercises/practice/yacht/.meta/config.json
Labels: x:size/tiny

#700 Sync zebra puzzle
  exercises/practice/zebra-puzzle/.meta/example.php
  exercises/practice/zebra-puzzle/ZebraPuzzleTest.php
Labels: x:action/sync, x:knowledge/elementary, x:module/practice-exercise, x:type/content, x:size/tiny, x:rep/tiny
