Repository exercism/php, pull requests merged in 2024-03, with the labels that each got.

#638 Test generator, step 1
  README.md
  contribution/generator/.env
  contribution/generator/.env.test
  contribution/generator/.gitignore
  contribution/generator/README.md
  contribution/generator/bin/console
  contribution/generator/composer.json
  contribution/generator/config/bundles.php
  contribution/generator/config/packages/cache.yaml
  contribution/generator/config/packages/framework.yaml
  contribution/generator/config/packages/routing.yaml
  contribution/generator/config/preload.php
  contribution/generator/config/routes.yaml
  contribution/generator/config/routes/framework.yaml
  contribution/generator/config/services.yaml
  contribution/generator/phpunit.xml.dist
  contribution/generator/public/index.php
  contribution/generator/src/Command/CreateTestsCommand.php
  contribution/generator/src/Controller/.gitignore
  contribution/generator/src/Kernel.php
  contribution/generator/src/TestGenerator.php
  contribution/generator/src/TrackData/CanonicalData.php
  contribution/generator/src/TrackData/CanonicalData/TestCase.php
  contribution/generator/src/TrackData/Exercise.php
  contribution/generator/src/TrackData/PracticeExercise.php
  contribution/generator/symfony.lock
  contribution/generator/tests/bootstrap.php
  phpunit.xml
Labels: x:action/create, x:knowledge/intermediate, x:module/generator, x:type/coding, x:size/large, x:rep/large

#655 CI Add back macOS test
  .github/workflows/exercise-tests-phpunit-9.yml
Labels: x:action/fix, x:knowledge/none, x:type/ci, x:size/tiny, x:rep/large

#656 CI Add PHPUnit 10 and PHP 8.3
  .github/workflows/exercise-tests-phpunit-10.yml
  composer.json
  exercises/practice/allergies/AllergiesTest.php
  exercises/practice/binary/BinaryTest.php
  exercises/practice/gigasecond/GigasecondTest.php
  exercises/practice/protein-translation/ProteinTranslationTest.php
Labels: x:action/improve, x:knowledge/none, x:type/ci, x:size/medium, x:rep/medium

#657 Better interface for Circular Buffer
  exercises/practice/circular-buffer/CircularBuffer.php
Labels: x:action/improve, x:knowledge/elementary, x:module/practice-exercise, x:type/content, x:size/small, x:rep/small

#654 Improve contributor experience
  .github/workflows/exercise-lint-phpcs-psr-12.yml
  README.md
  composer.json
Labels: x:action/improve, x:knowledge/none, x:type/ci, x:type/coding, x:size/medium, x:rep/medium

#665 Fix Meetup exercise tests
  exercises/practice/meetup/.meta/example.php
  exercises/practice/meetup/MeetupTest.php
Labels: x:action/fix, x:knowledge/elementary, x:module/practice-exercise, x:size/small, x:rep/small

#669 sieve: sync
  exercises/practice/sieve/.docs/instructions.md
Labels: x:size/tiny

#670 two-fer: sync
  exercises/practice/two-fer/.docs/instructions.md
  exercises/practice/two-fer/.docs/introduction.md
  exercises/practice/two-fer/.meta/config.json
Labels: x:size/tiny

#672 Drop MacOS from CI
  .github/workflows/exercise-tests-phpunit-9.yml
Labels: x:action/fix, x:knowledge/none, x:type/ci, x:size/tiny, x:rep/tiny

#671 Fix "class names" in Basics (long concept text)
  concepts/basic-syntax/about.md
Labels: x:action/fix, x:knowledge/elementary, x:module/concept, x:type/content, x:size/tiny, x:rep/tiny
