Repository exercism/php, pull requests merged in 2024-05, with the labels that each got.

#701 Sync minesweeper
  exercises/practice/minesweeper/.meta/config.json
  exercises/practice/minesweeper/.meta/example.php
  exercises/practice/minesweeper/Minesweeper.php
  exercises/practice/minesweeper/MinesweeperTest.php
Labels: x:action/sync, x:knowledge/elementary, x:module/practice-exercise, x:type/content, x:size/large, x:rep/large

#706 pig-latin: sync
  exercises/practice/pig-latin/.docs/instructions.md
  exercises/practice/pig-latin/.docs/introduction.md
  exercises/practice/pig-latin/.meta/config.json
Labels: x:size/tiny

#707 spiral-matrix: sync
  exercises/practice/spiral-matrix/.docs/instructions.md
  exercises/practice/spiral-matrix/.docs/introduction.md
Labels: x:size/tiny

#708 anagram: sync
  exercises/practice/anagram/.docs/instructions.md
  exercises/practice/anagram/.docs/introduction.md
Labels: x:size/tiny

#709 knapsack: sync
  exercises/practice/knapsack/.docs/instructions.md
  exercises/practice/knapsack/.docs/introduction.md
Labels: x:size/tiny

#710 kindergarten-garden: sync
  exercises/practice/kindergarten-garden/.docs/instructions.md
  exercises/practice/kindergarten-garden/.docs/introduction.md
Labels: x:size/tiny

#717 this update should fix #716 so that an empty function will not allow …
  exercises/concept/language-list/LanguageListTest.php
Labels: x:action/fix, x:knowledge/none, x:module/concept-exercise, x:type/content, x:size/small, x:rep/small

#718 Deprecate scale-generator
  config.json
Labels: x:action/sync, x:knowledge/elementary, x:module/practice-exercise, x:type/content, x:size/tiny, x:rep/tiny

#715 Sync dnd-character
  exercises/practice/dnd-character/.meta/example.php
  exercises/practice/dnd-character/.meta/tests.toml
  exercises/practice/dnd-character/DndCharacter.php
  exercises/practice/dnd-character/DndCharacterTest.php
Labels: x:action/sync, x:knowledge/elementary, x:module/practice-exercise, x:type/content, x:size/small, x:rep/small

#719 Sync pig-latin
  exercises/practice/pig-latin/.meta/example.php
  exercises/practice/pig-latin/PigLatinTest.php
Labels: x:action/sync, x:knowledge/elementary, x:module/practice-exercise, x:type/content, x:size/small, x:rep/small

#723 Fix arrays concept
  concepts/arrays/about.md
  concepts/arrays/introduction.md
  concepts/arrays/links.json
  exercises/concept/language-list/.docs/introduction.md
Labels: x:action/fix, x:knowledge/elementary, x:module/concept, x:type/content, x:size/tiny, x:rep/tiny

#725 pig-latin: sync
  exercises/practice/pig-latin/.docs/instructions.md
Labels: x:size/tiny
